<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Configurations>Debug;Release;SecureDebug</Configurations>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <OutputPath>$(SolutionDir)Bin\$(Configuration)\</OutputPath>
    <IntermediateOutputPath>$(SolutionDir)Obj\$(MSBuildProjectName)\$(Configuration)\</IntermediateOutputPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='SecureDebug|AnyCPU'">
    <DefineConstants>DEBUG;TRACE;ENABLE_SECURE_LOGS</DefineConstants>
    <OutputPath>$(SolutionDir)Bin\$(Configuration)\</OutputPath>
    <IntermediateOutputPath>$(SolutionDir)Obj\$(MSBuildProjectName)\$(Configuration)\</IntermediateOutputPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DefineConstants>TRACE</DefineConstants>
    <OutputPath>$(SolutionDir)Bin\$(Configuration)\</OutputPath>
    <IntermediateOutputPath>$(SolutionDir)Obj\$(MSBuildProjectName)\$(Configuration)\</IntermediateOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.Core" Version="4.0.6.1" />
    <PackageReference Include="AWSSDK.Polly" Version="4.0.6.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LukeBot.AWS\LukeBot.AWS.csproj" />
    <ProjectReference Include="..\LukeBot.Common\LukeBot.Common.csproj" />
    <ProjectReference Include="..\LukeBot.Logging\LukeBot.Logging.csproj" />
    <ProjectReference Include="..\LukeBot.Config\LukeBot.Config.csproj" />
    <ProjectReference Include="..\LukeBot.Services\LukeBot.Services.csproj" />
  </ItemGroup>

</Project>
